# Generated by Django 3.2.8 on 2021-10-13 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facilitator_notes', to='core.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notes', to='core.person')),
            ],
        ),
    ]
